# Color constants
TRANSPARENT="#1e1e2e"
BG="#181825"
FG="#cdd6f4"
ACCENT="#f5c2e7"
WINDOW=$BG
WINDOW_ACTIVE=$ACCENT


# Reloading config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloading done"


# Appearance
set -g status-style fg=$ACCENT,bg=$TRANSPARENT

set -g pane-border-style fg=$BG
set -g pane-active-border-style fg=$ACCENT

setw -g status-left-length 50
set -g status-left "#[bg=$BG] #S #[bg=$TRANSPARENT] "

setw -g window-status-format "#[bg=$WINDOW,fg=$FG,bold] #I #[default,bg=$BG] #W "
setw -g window-status-current-format "#[bg=$WINDOW_ACTIVE,fg=$BG,bold] #I #[default,bg=$BG] #W "
setw -g window-status-separator " "

DATE="#(date '+%Y %b %d | %H:%M')"
PREFIX="#{?client_prefix,<prefix>,}"
set -g status-right "$PREFIX #[bg=$ACCENT,fg=$BG,bold] $DATE "


# Window binds
bind -n M-H previous-window
bind -n M-L next-window
bind -n M-h previous-window
bind -n M-l next-window
bind -n M-Left previous-window
bind -n M-Right next-window

# Terminal color fix
set-option -sa terminal-overrides ",xterm*:Tc"


# Window numbering
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# Vim binds
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind P paste-buffer


# TPM and TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.config/tmux/plugins/tpm/tpm'
